#!/usr/bin/env expect
if {[lindex $argv 2] == ""} {
	send "usage: vpnpass path/to/file.ovpn username password/path/in/pass \[totp/path/in/pass\]\n"
	exit
}
set conf [lindex $argv 0];
set user [lindex $argv 1];
set pass_pw [lindex $argv 2];
set pass_otp [lindex $argv 3];
spawn sudo openvpn --config $conf
expect "Enter Auth Username:"
send "$user\n"
expect "Enter Auth Password:"
set pw [exec pass "$pass_pw"]
send "$pw\n"
if {"$pass_otp" != ""} {
	expect "Enter TOTP:"
	set otp [exec pass otp "$pass_otp"]
	send "$otp\n"
}
interact
